### ISSUE TITLE
Simple theorem generates "Cannot parse a `sorry` tactic on root." Error

### ISSUE THREAD

**Issue by sethahrenbach** [deepseek-ai/DeepSeek-Prover-V1.5#4] opened 2024-08-28 14:43 UTC
My theorem file:
```
{"name": "binaryAdditionLength", "split": "valid", "informal_prefix": "/-- Let `binaryAddition` be a function that takes two lists of booleans, each representing a binary number of at most 10 bits, and returns a list of booleans representing their sum modulo 1024. Prove that the length of the output is at most 10 bits. -/\n", "formal_statement": "theorem binaryAdditionLength (s t : List Bool) :\n  (binaryAddition s t).length ≤ 10 :=", "goal": "s t : List Bool\n⊢ (binaryAddition s t).length ≤ 10", "header": "def binaryAddition (s t : List Bool) : List Bool :=\n  let rec loop (i : Nat) (carry : Bool) (acc : List Bool) : List Bool :=\n    match s.get? i, t.get? i with\n    | some a, some b => \n        let sum := (if a then 1 else 0) + (if b then 1 else 0) + (if carry then 1 else 0)\n        loop (i+1) (sum ≥ 2) ((sum % 2 = 1) :: acc)\n    | some a, none => \n        let sum := (if a then 1 else 0) + (if carry then 1 else 0)\n        loop (i+1) (sum = 2) ((sum % 2 = 1) :: acc)\n    | none, some b => \n        let sum := (if b then 1 else 0) + (if carry then 1 else 0)\n        loop (i+1) (sum = 2) ((sum % 2 = 1) :: acc)\n    | none, none => \n        if carry then true::acc else acc\n  termination_by _ i _ _ => (max s.length t.length) - i\n  (loop 0 false []).reverse.take 10\n\n"}
```
As you can see it requires no imports and does not contain any `sorry` tactics.

**Comment by sethahrenbach** [comment] 2024-08-28 15:41
Looks like a syntax error in the `header` content will trigger the `sorry` error. It would be useful to have the syntax errors surfaced.

**Comment by fzyzcjy** [comment] 2024-08-29 08:43
+1 I see

```
Process SearchProcess-38:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/host_home/research/code/third_party_inline/DeepSeek-Prover-V1.5/prover/workers/search.py", line 66, in run
    for sample, info in sample_generator:
  File "/host_home/research/code/third_party_inline/DeepSeek-Prover-V1.5/prover/algorithms/rmax_tree_search.py", line 267, in sample
    self.root, sample_count, yield_cache = self._tree_setup(data)
                                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/host_home/research/code/third_party_inline/DeepSeek-Prover-V1.5/prover/algorithms/rmax_tree_search.py", line 167, in _tree_setup
    assert root_sorry.result['pass'], "Cannot parse a `sorry` tactic on root."
AssertionError: Cannot parse a `sorry` tactic on root.
```

**Comment by saisurbehera** [comment] 2024-09-01 20:30
+1, has anyone found a fix for this
```
AssertionError: Cannot parse a `sorry` tactic on root.
Process SearchProcess-327:
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/root/DeepSeek-Prover-V1.5/prover/workers/search.py", line 64, in run
    for sample, info in sample_generator:
  File "/root/DeepSeek-Prover-V1.5/prover/algorithms/rmax_tree_search.py", line 267, in sample
    self.root, sample_count, yield_cache = self._tree_setup(data)
                                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/DeepSeek-Prover-V1.5/prover/algorithms/rmax_tree_search.py", line 167, in _tree_setup
    assert root_sorry.result['pass'], "Cannot parse a `sorry` tactic on root."
```

**Comment by longdct** [comment] 2024-09-24 01:30
This bug was caused by REPL dependency of mathlib4. I removed that package and built it again, and it worked.
```
cd mathlib4
rm -rf .lake/packages/REPL/
lake build REPL
```

**Closed as completed** 2024-09-24 12:12 UTC
